### ISSUE TITLE
Bazel cache miss in /cas disables using remote cache

### ISSUE THREAD

**Issue by alexv-smirnov** [yandex/yatool#12]
Some files may not exist in the remote cache, for instance if they have been washed out by the more fresh ones. The cache must not become completely useless because of that.

Current behaviour:
There's no logic to process 404 (Not found) error from the remote cache /cas folder, if the response for the metadata in /ac folder had been successfully processed before. Uncompressed response goes to zstd decoder, and fails there. After several failed attempts (which are completely useless after such a response), the whole remote cache gets disabled.

Desired behaviour:
1. If the remote cache response came without the 'Content-Encoding' header, yatool must skip the Decoding phase. There's no guarantee that the server's responses are in fact encoded as we suggested it to in our requests.
2. If the remote cache returned 404 (Not found) for either /ac or /cas requests, yatool must recompile this particular object, without disabling the whole cache.

**Comment by frazenshtein** [comment]
Thanks for report! We have corrected the behavior, now the cache works as expected in case of these problems
