### ISSUE TITLE
"include" in ya package's package.json overrides "params" section

### ISSUE THREAD

**Issue by Krock21** [yandex/yatool#18]
I tried to add "include" to my package.json and noticed that "params" section stopped working.
It happens only when `include` is used.

How to reproduce:

`test.json`:
```
{
    "include": [
      "FULL-PATH-HERE/empty.json",
    ],
    "meta": {
        "name": "docker-test",
        "maintainer": "docker-test",
        "description": "docker-test",
        "version": "{revision}",
    },
    "params": {
        "format": "docker",
    },
    "build": {},
    "data": [],
}
```

`empty.json`:
```
{
    "meta": {
        "name": "empty",
        "maintainer": "empty",
        "description": "empty",
        "version": "{revision}",
    },
    "build": {},
    "data": [],
}
```

```
$ ya package test.json
...
Creating tar package docker-test
...
```

Removing `include` section from `test.json` gives this:
```
$ ya package test.json
...
Creating docker package docker-test
...
```

I also notices that using `include` erases `docker_target` and `docker_build_arg` from params

**Comment by Krock21** [comment]
Seems like `params` from included file override `params` from test one

**Comment by frazenshtein** [comment]
Hi! Thanks for the report and the minimal example to reproduce the problem. 
The error has been fixed, it will soon reach GitHub. The release of ya with the fix will take place this week.
