### ISSUE TITLE
Python interpreter is not found in this system, please, install python

### ISSUE THREAD

**Issue by Krock21** [yandex/yatool#19]
Tried to build some target in `ydb-platform/ydb` and saw `Python interpreter is not found in this system, please, install python`

How to reproduce:
1. Checkout ydb to `$HOME/ydb`
2. Run  `docker run --rm -it -v $HOME/ydb:/ydb ubuntu:focal /bin/bash -c "apt update && apt install -y python3.8-dev; /ydb/ya make -DUSE_ARCADIA_PYTHON=no -DUSE_LOCAL_PYTHON -DPYTHON_CONFIG=python3.8-config -DPYTHON_BIN=python3.8 /ydb/ydb/library/yql/udfs/common/python/system_python/python3_8"`

Ya tried to find `python` or `python3` and failed, while in my system I have `python3.8` installed.

I think it is worth checking other python executables, like `python3.8`, here: https://github.com/yandex/yatool/blob/main/ya#L14

**Comment by frazenshtein** [comment]
Hello! Thanks for report!

There are a lot of python versions and testing them in this script is not free - it takes some time on the critical path. Also, a large number of tools can expect command `env python` to work correctly.

You can solve the problem for yourself in several ways:
1. Manually make an alias
2. Add `update-alternatives --install /usr/bin/python python /usr/bin/python3.8 10` to you script
