### ISSUE TITLE
Building open source application with YA

### ISSUE THREAD

**Issue by DenVilk** [yandex/yatool#3]
Is there any way to build my own Python application using this tool? Maybe is there any documentation for that?

**Comment by frazenshtein** [comment]
Hello! Sorry for the delay.

Sure,you can use yatool to create your own applications, just keep the following in mind:
  - https://github.com/yandex/yatool?tab=readme-ov-file#warning---bumpy-road-ahead
  - The easiest way to use yatool without stable releases is to fork the repository, create or move your project to the repository and add the necessary ya.make files.
  - We don't publish all the contrib modules we have in our internal repository, but currently the following are available for open source use: https://github.com/yandex/yatool/tree/main/contrib/python

> Maybe is there any documentation for that?

Not long ago we wrote an open source version of the documentation, which is available here: https://github.com/yandex/yatool/tree/main/build/docs/ru
We expect the English version by the end of the year.

Also you can take a look at tutorial examples like: https://github.com/yandex/yatool/tree/main/devtools/examples/tutorials/python/program_with_lib
https://github.com/yandex/yatool/tree/main/build/docs/ru
