### ISSUE TITLE
Simple project example

### ISSUE THREAD

**Issue by mutexed** [yandex/yatool#6]
Hello, I'm trying to use yatool for building simple c++ app. Can you provide very simple example of some project tree?

Here what I've done:
1) built yatool using itself and got a ya binary path, e.g. `~/.ya/build/symres/.../ya-bin`
2) created new directory `test-ya-project`, added `.arcadia.root` and `ya.conf` files
3) added subdirectory `test-proj` and `main.cpp` with "Hello world" and ya.make file
```
PROGRAM(test-proj)
SRCS(
    main.cpp
)
END()
```

Now, when I'm trying to build it calling `~/.ya/build/symres/.../ya-bin make test-proj` being in `test-ya-project` directory, I'm  getting error `Cannot find config mapping.conf.json`. I found this file in build directory in yatool, then I just copied all build directory to my test-ya-project directory. It wasn't enough: calling ya make still caused an error, because it tried to use `util`, `library` and `contrib` from yatool repository. After coping all of these directories it's finally built successfully.

So, I'm trying to understand, do I really need to copy these yatool dependencies to my "monorepository" `test-ya-project`? Or it caused because of lack of some configuration from my side?

**Comment by frazenshtein** [comment]
Greetings!

> still caused an error, because it tried to use util, library and contrib from yatool repository
> So, I'm trying to understand, do I really need to copy these yatool dependencies to my "monorepository" test-ya-project? Or it caused because of lack of some configuration from my side?

The current repository consists of the modules and libraries necessary to build the build system itself. Indeed, not all of these dependencies are needed to build an arbitrary project, and at the same time, the current set may not be enough for some purposes.

Therefore, you did everything right. At the moment, the easiest way to make experiments is by forking and placing your project in the repository.

In the future, we plan to expand the documentation and make build system releases that will include only the necessary parts.

**Comment by mutexed** [comment]
I see, thanks for reply! Waiting for the documentation :)
